# 设置端口号
# 设置应用上下文路径
server:
  port: 8080
  servlet:
    context-path: /start 
  # 开启debug输出
  debug: true

# 测试自定义属性
demo:
  code: ${random.value}
  name: Name
  hobby: 
    - 看电影
    - 游泳
    
    
# 设置日志是否彩色输出
spring: 
  output: 
    ansi: 
      enabled: DETECT
# 设置日志输出到文本
logging: 
  file: /var/log