# 设置端口号
# 设置应用上下文路径
server:
  port: 8888
  servlet:
    context-path: /start 
  # 开启debug输出 没有用?
  debug: true

# 测试自定义属性
demo:
  code: ${random.value}
  name: Name
  hobby: 
    - 看电影
    - 游泳
    
    
# 设置日志是否彩色输出
spring: 
  output: 
    ansi: 
      enabled: DETECT
#配置数据源
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/start_database?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
#    initialSize: 5     
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,log4j
#    connectionProperties: druid.stat.mergeSql=true
#
#druid: 
#  stat: 
#    slowSqlMillis: 5000
#    
#mybatis-plus: 
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  typeAliasesPackage: top.inick.start.domain
    
    
# 当然可以使用 自动配置进行，即以spring.datasource开头的
validationQuery: select 1
mysql: 
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/start_database?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: root
  maxActive: 200

# 设置日志输出到文本
logging: 
  file: /var/log
  # 设置输出级别
#  level:
#    root: debug 
  
  

